<?php
namespace Database\Seeds;

use Framework\Model\Types\DatabaseModel;
use Framework\Schema\Seed;

class FillCountriesTable extends Seed
{
    public function getName()
    {
        return 'fill_countries_table';
    }

    public function getClass()
    {
        return 'App\\Models\\System\\Country';
    }
    
    public function getFields()
    {
        return [
            'name',
            'alias',
            'code',
            'pattern',
            'flag'
        ];
    }

    public function up()
    {
        return [
            //`name`, `alias`, `code`, `pattern`, `flag`
            ['﻿Russia (Россия)', '', '+7', '\\(\\d\\d\\d\\)\\d\\d\\d-\\d\\d-\\d\\d', -660],
            ['Afghanistan (‫افغانستان‬‎)', '', '+93', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2311],
            ['Albania (Shqipëri)', '', '+355', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1034],
            ['Algeria', '', '+213', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -528],
            ['American Samoa', '', '+1684', '\\d\\d\\d-\\d\\d\\d\\d', -1562],
            ['Andorra', '', '+376', '\\d\\d\\d-\\d\\d\\d', -594],
            ['Angola', '', '+244', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1947],
            ['Anguilla', '', '+1264', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1980],
            ['Antigua Barbuda', '', '+1268', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -869],
            ['Argentina', '', '+54', '\\d-\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -2377],
            ['Armenia (Հայաստան)', '', '+374', '\\d\\d-\\d\\d\\d\\d\\d\\d', -176],
            ['Aruba', '', '+297', '\\d\\d\\d-\\d\\d\\d\\d', -792],
            ['Ascension Island', '', '+247', '\\d\\d\\d\\d', -55],
            ['Australia', '', '+61', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1716],
            ['Austria (Österreich)', '', '+43', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -1331],
            ['Azerbaijan (Azərbaycan)', '', '+994', '\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d', -1243],
            ['Bahamas', '', '+1242', '\\d\\d\\d-\\d\\d\\d\\d', -363],
            ['Bahrain (‫البحرين‬‎)', '', '+973', '\\d\\d\\d\\d-\\d\\d\\d\\d', -1496],
            ['Bangladesh (বাংলাদেশ)', '', '+880', '\\d\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -1771],
            ['Barbados', '', '+1246', '\\d\\d\\d-\\d\\d\\d\\d', -1573],
            ['Belarus (Беларусь)', '', '+375', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1100],
            ['Belgium (België)', '', '+32', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', 0],
            ['Belize', '', '+501', '\\d\\d\\d-\\d\\d\\d\\d', -484],
            ['Benin (Bénin)', '', '+229', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1298],
            ['Bermuda', '', '+1441', '\\d\\d\\d-\\d\\d\\d\\d', -1914],
            ['Bhutan (འབྲུག)', '', '+975', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1848],
            ['Bolivia', '', '+591', '\\d\\d\\d\\d\\d\\d\\d\\d', -1650],
            ['Bosnia &amp; Herzegovina (Босна и Херцеговина)', '', '+387', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -1584],
            ['Botswana', '', '+267', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -2707],
            ['Brazil (Brasil)', '', '+55', '\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -770],
            ['British Indian Ocean Territory', '', '+246', '\\d\\d\\d-\\d\\d\\d\\d', -55],
            ['British Virgin Islands', '', '+1284', '\\d\\d\\d-\\d\\d\\d\\d', -1408],
            ['Brunei', '', '+673', '\\d\\d\\d-\\d\\d\\d\\d', -1683],
            ['Bulgaria (България)', '', '+359', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -2586],
            ['Burkina Faso', '', '+226', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -726],
            ['Burundi (Uburundi)', '', '+257', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1892],
            ['Cambodia (កម្ពុជា)', '', '+855', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -242],
            ['Cameroon (Cameroun)', '', '+237', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2057],
            ['Canada', '', '+1', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1375],
            ['Cape Verde (Kabu Verdi)', '', '+238', '\\d\\d\\d-\\d\\d-\\d\\d', -2652],
            ['Caribbean Netherlands', '', '+599', '\\d\\d\\d-\\d\\d\\d\\d', -2719],
            ['Cayman Islands', '', '+1345', '\\d\\d\\d-\\d\\d\\d\\d', -308],
            ['Central African Republic (République centrafricaine)', '', '+236', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1837],
            ['Chad (Tchad)', '', '+235', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -814],
            ['Chile', '', '+56', '\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -1342],
            ['China (中国)', '', '+86', '\\d\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -825],
            ['Colombia', '', '+57', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -330],
            ['Comoros (‫جزر القمر‬‎)', '', '+269', '\\d\\d\\d-\\d\\d-\\d\\d', -1430],
            ['Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', '', '+243', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1518],
            ['Congo (Republic) (Congo-Brazzaville)', '', '+242', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1793],
            ['Cook Islands', '', '+682', '\\d\\d-\\d\\d\\d', -2267],
            ['Costa Rica', '', '+506', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2090],
            ['Côte d’Ivoire', '', '+225', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1661],
            ['Croatia (Hrvatska)', '', '+385', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -902],
            ['Cuba', '', '+53', '\\d-\\d\\d\\d\\d\\d\\d\\d', -748],
            ['Curaçao', '', '+599', '\\d-\\d\\d\\d-\\d\\d\\d\\d', -2729],
            ['Cyprus (Κύπρος)', '', '+357', '\\d\\d-\\d\\d\\d\\d\\d\\d', -561],
            ['Czech Republic (Česká republika)', '', '+420', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -2256],
            ['Denmark (Danmark)', '', '+45', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1386],
            ['Djibouti', '', '+253', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2101],
            ['Dominica', '', '+1767', '\\d\\d\\d-\\d\\d\\d\\d', -2432],
            ['Dominican Republic (República Dominicana)', '', '+1809', '\\d\\d\\d-\\d\\d\\d\\d', -1529],
            ['Ecuador', '', '+593', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1188],
            ['Egypt (‫مصر‬‎)', '', '+20', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2201],
            ['El Salvador', '', '+503', '\\d\\d\\d\\d-\\d\\d\\d\\d', -1639],
            ['Equatorial Guinea (Guinea Ecuatorial)', '', '+240', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1507],
            ['Eritrea', '', '+291', '\\d-\\d\\d\\d-\\d\\d\\d', -715],
            ['Estonia (Eesti)', '', '+372', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2410],
            ['Ethiopia', '', '+251', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2443],
            ['Falkland Islands (Islas Malvinas)', '', '+500', '\\d\\d\\d\\d\\d', -2762],
            ['Faroe Islands (Føroyar)', '', '+298', '\\d\\d\\d\\d\\d\\d', -1111],
            ['Fiji', '', '+679', '\\d\\d\\d-\\d\\d\\d\\d', -1859],
            ['Finland (Suomi)', '', '+358', '\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -1903],
            ['France', '', '+33', '\\d-\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1012],
            ['French Guiana (Guyane française)', '', '+594', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2234],
            ['French Polynesia (Polynésie française)', '', '+689', '\\d\\d-\\d\\d-\\d\\d', -1705],
            ['Gabon', '', '+241', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -880],
            ['Gambia', '', '+220', '\\d\\d\\d-\\d\\d\\d\\d', -627],
            ['Georgia (საქართველო)', '', '+995', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -858],
            ['Germany (Deutschland)', '', '+49', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d\\d', -2509],
            ['Ghana (Gaana)', '', '+233', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2112],
            ['Gibraltar', '', '+350', '\\d\\d\\d\\d\\d\\d\\d\\d', -275],
            ['Greece (Ελλάδα)', '', '+30', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -165],
            ['Greenland (Kalaallit Nunaat)', '', '+299', '\\d\\d-\\d\\d-\\d\\d', -1760],
            ['Grenada', '', '+1473', '\\d\\d\\d-\\d\\d\\d\\d', -2399],
            ['Guadeloupe', '', '+590', '\\d\\d\\d-\\d\\d-\\d\\d\\d\\d', -407],
            ['Guam', '', '+1671', '\\d\\d\\d-\\d\\d\\d\\d', -2366],
            ['Guatemala', '', '+502', '\\d\\d\\d\\d-\\d\\d\\d\\d', -935],
            ['Guinea (Guinée)', '', '+224', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2575],
            ['Guinea-Bissau (Guiné Bissau)', '', '+245', '\\d\\d-\\d\\d\\d\\d', -1925],
            ['Guyana', '', '+592', '\\d\\d\\d-\\d\\d\\d\\d', -803],
            ['Haiti', '', '+509', '\\d\\d-\\d\\d-\\d\\d\\d\\d', -319],
            ['Honduras', '', '+504', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2156],
            ['Hong Kong (香港)', '', '+852', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2696],
            ['Hungary (Magyarország)', '', '+36', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -682],
            ['Iceland (Ísland)', '', '+354', '\\d\\d\\d-\\d\\d\\d\\d', -1991],
            ['India (भारत)', '', '+91', '\\d\\d-\\d\\d-\\d\\d\\d\\d\\d\\d', -1694],
            ['Indonesia', '', '+62', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1958],
            ['Iran (‫ایران‬‎)', '', '+98', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2013],
            ['Iraq (‫العراق‬‎)', '', '+964', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -649],
            ['Ireland', '', '+353', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1969],
            ['Israel (‫ישראל‬‎)', '', '+972', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -341],
            ['Italy (Italia)', '', '+39', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -143],
            ['Jamaica', '', '+1876', '\\d\\d\\d-\\d\\d\\d\\d', -1727],
            ['Japan (日本)', '', '+81', '\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -429],
            ['Jordan (‫الأردن‬‎)', '', '+962', '\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -1463],
            ['Kazakhstan (Казахстан)', '', '+7', '\\(\\d\\d\\d\\)\\d\\d\\d-\\d\\d-\\d\\d', -1210],
            ['Kenya', '', '+254', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -2630],
            ['Kiribati', '', '+686', '\\d\\d\\d\\d\\d', -374],
            ['Kuwait (‫الكويت‬‎)', '', '+965', '\\d\\d\\d-\\d\\d\\d\\d\\d', -2487],
            ['Kyrgyzstan (Кыргызстан)', '', '+996', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1617],
            ['Laos (ລາວ)', '', '+856', '\\d\\d-\\d\\d-\\d\\d\\d-\\d\\d\\d', -451],
            ['Latvia (Latvija)', '', '+371', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -1936],
            ['Lebanon (‫لبنان‬‎)', '', '+961', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -1254],
            ['Lesotho', '', '+266', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2190],
            ['Liberia', '', '+231', '\\d-\\d\\d\\d-\\d\\d\\d', -2068],
            ['Libya (‫ليبيا‬‎)', '', '+218', '\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -132],
            ['Liechtenstein', '', '+423', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -979],
            ['Lithuania (Lietuva)', '', '+370', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -1122],
            ['Luxembourg', '', '+352', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1474],
            ['Macau (澳門)', '', '+853', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2597],
            ['Macedonia (FYROM) (Македонија)', '', '+389', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -1353],
            ['Madagascar (Madagasikara)', '', '+261', '\\d\\d-\\d\\d-\\d\\d\\d-\\d\\d', -1287],
            ['Malawi', '', '+265', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2145],
            ['Malaysia', '', '+60', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1870],
            ['Maldives', '', '+960', '\\d\\d\\d-\\d\\d\\d\\d', -616],
            ['Mali', '', '+223', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2520],
            ['Malta', '', '+356', '\\d\\d\\d\\d-\\d\\d\\d\\d', -1551],
            ['Marshall Islands', '', '+692', '\\d\\d\\d-\\d\\d\\d\\d', -1144],
            ['Martinique', '', '+596', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -198],
            ['Mauritania (‫موريتانيا‬‎)', '', '+222', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -253],
            ['Mauritius (Moris)', '', '+230', '\\d\\d\\d-\\d\\d\\d\\d', -2179],
            ['Mexico (México)', '', '+52', '\\d-\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2024],
            ['Micronesia', '', '+691', '\\d\\d\\d-\\d\\d\\d\\d', -1738],
            ['Moldova (Republica Moldova)', '', '+373', '\\d\\d\\d-\\d\\d-\\d\\d\\d', -2685],
            ['Monaco', '', '+377', '\\d-\\d\\d-\\d\\d-\\d\\d-\\d\\d', -913],
            ['Mongolia (Монгол)', '', '+976', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2553],
            ['Montenegro (Crna Gora)', '', '+382', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -2167],
            ['Montserrat', '', '+1664', '\\d\\d\\d-\\d\\d\\d\\d', -583],
            ['Morocco', '', '+212', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -2333],
            ['Mozambique (Moçambique)', '', '+258', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -638],
            ['Myanmar (Burma) (မြန်မာ)', '', '+95', '\\d-\\d\\d\\d-\\d\\d\\d\\d', -11],
            ['Namibia (Namibië)', '', '+264', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1881],
            ['Nauru', '', '+674', '\\d\\d\\d-\\d\\d\\d\\d', -1749],
            ['Nepal (नेपाल)', '', '+977', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -110],
            ['Netherlands (Nederland)', '', '+31', '\\d-\\d\\d\\d\\d\\d\\d\\d\\d', -1441],
            ['New Caledonia (Nouvelle-Calédonie)', '', '+687', '\\d\\d-\\d\\d-\\d\\d', -1276],
            ['New Zealand', '', '+64', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1540],
            ['Nicaragua', '', '+505', '\\d\\d\\d\\d-\\d\\d\\d\\d', -154],
            ['Niger (Nijar)', '', '+227', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -550],
            ['Nigeria', '', '+234', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2476],
            ['Niue', '', '+683', '\\d\\d\\d\\d', -2079],
            ['Norfolk Island', '', '+6723', '\\d-\\d\\d\\d\\d\\d', -209],
            ['Northern Mariana Islands', '', '+1', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -704],
            ['North Korea (조선 민주주의 인민 공화국)', '', '+850', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1804],
            ['Norway (Norge)', '', '+47', '\\d\\d\\d-\\d\\d-\\d\\d\\d', -836],
            ['Oman (‫عُمان‬‎)', '', '+968', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2454],
            ['Pakistan (‫پاکستان‬‎)', '', '+92', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -2035],
            ['Palau', '', '+680', '\\d\\d\\d-\\d\\d\\d\\d', -231],
            ['Palestine (‫فلسطين‬‎)', '', '+970', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1199],
            ['Panama (Panamá)', '', '+507', '\\d\\d\\d\\d-\\d\\d\\d\\d', -847],
            ['Papua New Guinea', '', '+675', '\\d\\d\\d-\\d\\d\\d\\d', -1485],
            ['Paraguay', '', '+595', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -2344],
            ['Peru (Perú)', '', '+51', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -946],
            ['Philippines', '', '+63', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1815],
            ['Poland (Polska)', '', '+48', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1177],
            ['Portugal', '', '+351', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -517],
            ['Puerto Rico', '', '+1787', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -473],
            ['Qatar (‫قطر‬‎)', '', '+974', '\\d\\d\\d\\d-\\d\\d\\d\\d', -462],
            ['Réunion (La Réunion)', '', '+262', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -264],
            ['Romania (România)', '', '+40', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -671],
            ['Rwanda', '', '+250', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -2674],
            ['Samoa', '', '+685', '\\d\\d\\d\\d\\d\\d', -2300],
            ['San Marino', '', '+378', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -2123],
            ['São Tomé &amp; Príncipe (São Tomé e Príncipe)', '', '+239', '\\d\\d\\d-\\d\\d\\d\\d', -2388],
            ['Saudi Arabia (‫المملكة العربية السعودية‬‎)', '', '+966', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -33],
            ['Senegal', '', '+221', '\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d', -2134],
            ['Serbia (Србија)', '', '+381', '\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -2465],
            ['Seychelles', '', '+248', '\\d-\\d\\d\\d-\\d\\d\\d', -1045],
            ['Sierra Leone', '', '+232', '\\d\\d-\\d\\d\\d\\d\\d\\d', -737],
            ['Singapore', '', '+65', '\\d\\d\\d\\d-\\d\\d\\d\\d', -22],
            ['Sint Maarten', '', '+1721', '\\d\\d\\d-\\d\\d\\d\\d', -2773],
            ['Slovakia (Slovensko)', '', '+421', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -2212],
            ['Slovenia (Slovenija)', '', '+386', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -1221],
            ['Solomon Islands', '', '+677', '\\d\\d\\d-\\d\\d\\d\\d', -1067],
            ['Somalia (Soomaaliya)', '', '+252', '\\d\\d-\\d\\d\\d\\d\\d\\d', -1364],
            ['South Africa', '', '+27', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2355],
            ['South Korea (대한민국)', '', '+82', '\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d', -2245],
            ['South Sudan (‫جنوب السودان‬‎)', '', '+211', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -2741],
            ['Spain (España)', '', '+34', '\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d', -1155],
            ['Sri Lanka (ශ්‍රී ලංකාව)', '', '+94', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2641],
            ['St. Barthélemy (Saint-Barthélemy)', '', '+590', '\\d\\d\\d-\\d\\d-\\d\\d\\d\\d', -1012],
            ['St. Helena', '', '+290', '\\d\\d-\\d\\d\\d', -495],
            ['St. Kitts &amp; Nevis', '', '+1869', '\\d\\d\\d-\\d\\d\\d\\d', -99],
            ['St. Lucia', '', '+1758', '\\d\\d\\d-\\d\\d\\d\\d', -1397],
            ['St. Martin (Saint-Martin (partie française))', '', '+590', '\\d\\d\\d-\\d\\d-\\d\\d\\d\\d', -55],
            ['St. Pierre &amp; Miquelon (Saint-Pierre-et-Miquelon)', '', '+508', '\\d\\d-\\d\\d-\\d\\d', -1078],
            ['St. Vincent &amp; Grenadines', '', '+1784', '\\d\\d\\d-\\d\\d\\d\\d', -2619],
            ['Sudan (‫السودان‬‎)', '', '+249', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -352],
            ['Suriname', '', '+597', '\\d\\d\\d-\\d\\d\\d\\d', -2663],
            ['Swaziland', '', '+268', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2278],
            ['Sweden (Sverige)', '', '+46', '\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d', -385],
            ['Switzerland (Schweiz)', '', '+41', '\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d', -1320],
            ['Syria (‫سوريا‬‎)', '', '+963', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1826],
            ['Taiwan (台灣)', '', '+886', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -506],
            ['Tajikistan', '', '+992', '\\d\\d\\d-\\d\\d-\\d\\d\\d\\d', -187],
            ['Tanzania', '', '+255', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -2289],
            ['Thailand (ไทย)', '', '+66', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -957],
            ['Timor-Leste', '', '+670', '\\d\\d\\d\\d-\\d\\d\\d\\d', -2784],
            ['Togo', '', '+228', '\\d\\d-\\d\\d-\\d\\d-\\d\\d', -605],
            ['Tokelau', '', '+690', '\\d\\d\\d\\d', -2751],
            ['Tonga', '', '+676', '\\d\\d\\d-\\d\\d\\d\\d', -1089],
            ['Trinidad &amp; Tobago', '', '+1868', '\\d\\d\\d-\\d\\d\\d\\d', -440],
            ['Tunisia', '', '+216', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -539],
            ['Turkey (Türkiye)', '', '+90', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -1606],
            ['Turkmenistan', '', '+993', '\\d\\d-\\d\\d\\d\\d\\d\\d', -2542],
            ['Turks &amp; Caicos Islands', '', '+1649', '\\d\\d\\d-\\d\\d\\d\\d', -1309],
            ['Tuvalu', '', '+688', '\\d\\d\\d\\d\\d\\d', -286],
            ['U.S. Virgin Islands', '', '+1340', '\\d\\d\\d-\\d\\d\\d\\d', -1408],
            ['Uganda', '', '+256', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -1166],
            ['Ukraine (Україна)', '', '+380', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2002],
            ['United Arab Emirates (‫الإمارات العربية المتحدة‬‎)', '', '+971', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2223],
            ['United Kingdom', '', '+44', '\\d\\d\\d\\d-\\d\\d\\d\\d\\d\\d', -55],
            ['United States', '', '+1', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -44],
            ['Uruguay', '', '+598', '\\d\\d-\\d\\d\\d-\\d\\d\\d', -2608],
            ['Uzbekistan (Oʻzbekiston)', '', '+998', '\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d', -1001],
            ['Vanuatu', '', '+678', '\\d\\d\\d-\\d\\d\\d\\d', -1265],
            ['Vatican City (Città del Vaticano)', '', '+379', '06-698\\d-\\d\\d\\d\\d', -2322],
            ['Venezuela', '', '+58', '\\d\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -1056],
            ['Vietnam (Việt Nam)', '', '+84', '\\d\\d-\\d\\d\\d-\\d\\d-\\d\\d', -968],
            ['Wallis Futuna', '', '+681', '\\d\\d-\\d\\d-\\d\\d', -1012],
            ['Yemen (‫اليمن‬‎)', '', '+967', '\\d\\d\\d-\\d\\d\\d-\\d\\d\\d', -1672],
            ['Zambia', '', '+260', '\\d\\d-\\d\\d\\d\\d\\d\\d\\d', -1595],
            ['Zimbabwe', '', '+263', '\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', -2046]
        ];
    }
}